# Generated by Django 4.1.7 on 2023-03-22 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio',
            field=models.FileField(default=None, null=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])], verbose_name='Музыка'),
        ),
    ]
