# Generated by Django 4.1.7 on 2023-03-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0002_walletuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_info', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
