# Generated by Django 4.1.7 on 2023-03-22 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0002_video_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='audio',
            field=models.FileField(default=None, null=True, upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])], verbose_name='Музыка'),
        ),
    ]
