# Generated by Django 4.1.7 on 2023-03-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0003_audio_alter_video_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_path',
            field=models.CharField(max_length=500),
        ),
    ]
