# Generated by Django 4.1.7 on 2023-03-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0004_alter_audio_audio_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('code', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
