# Generated by Django 4.1.7 on 2023-03-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0005_phonecodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(null=True, upload_to='image/', verbose_name='Обложка'),
        ),
    ]
